# Baseline OAuth2-Proxy. OIDC-first defaults for external providers.
oauth2:
  autoscaling:
    enabled: true
  config:
    existingSecret: oauth2-proxy-secret
    configFile: |-
      provider = "oidc"
      oidc_issuer_url = "https://plex-oidc.example.com"
      proxy_prefix = "/oauth2"
      redirect_url = "https://auth.example.com/oauth2/callback"
      upstreams = [ "file:///dev/null", "file:///etc/oauth2-proxy/static/#/oauth2/static/" ]
      reverse_proxy = true
      code_challenge_method = "S256"
      cookie_name = "_oauth2_proxy"
      cookie_domains = [ ".example.com" ]
      cookie_secure = true
      cookie_httponly = true
      cookie_expire = "168h"
      cookie_refresh = "1h"
      whitelist_domains = [ "*.example.com" ]
      skip_auth_routes = [
        "GET=^/probe",
        "GET=^/oauth2/probe",
        "GET=^/oauth2/static",
        "^/metrics",
        "^/oauth2/metrics"
      ]
      skip_provider_button = true
      real_client_ip_header = "X-Forwarded-For"
      show_debug_on_error = false
  deploymentAnnotations: {}
  ingress:
    annotations: {}
    enabled: true
    hosts: [auth.example.com]
    path: /oauth2
    pathType: Prefix
  service:
    portNumber: 4180
onepassworditem:
  enabled: true
  defaultVault: Kubernetes
  items:
    - item: oauth2-proxy
      name: oauth2-proxy-secret
